// packages/react-library/src/Table/TableFilter.tsx
import React from 'react';

interface TableFilterProps {
    filterText: string;
    onFilterChange: (text: string) => void;
}

const TableFilter = ({
    filterText,
    onFilterChange
}: TableFilterProps) => {
    return (
        <div className="table-controls">
            <input
                type="text"
                placeholder="Filter..."
                value={filterText}
                onChange={(e) => onFilterChange(e.target.value)}
                className="filter-input"
            />
        </div>
    );
};

export default TableFilter;

// packages/stencil-components/src/components/table/table-components/TableFilter.tsx
import { h } from '@stencil/core';

interface TableFilterProps {
    filterText: string;
    onFilterInput: (event: Event) => void;
}

export const TableFilter = ({ filterText, onFilterInput }: TableFilterProps) => (
    <div class="table-controls">
        <input
            type="text"
            placeholder="Filter..."
            value={filterText}
            onInput={onFilterInput}
            class="filter-input"
        />
    </div>
);
