// packages/react-library/src/Button/Button.tsx
import React from 'react';
import './Button.scss';

export interface ButtonProps {
  /**
   * The button variant style
   */
  variant?: 'primary' | 'secondary' | 'outline' | 'danger';

  /**
   * The button size
   */
  size?: 'small' | 'medium' | 'large';

  /**
   * If true, the button is disabled
   */
  disabled?: boolean;

  /**
   * If true, the button will take full width of container
   */
  fullWidth?: boolean;

  /**
   * Emitted when the button is clicked
   */
  onClick?: (event: React.MouseEvent<HTMLButtonElement>) => void;

  children?: React.ReactNode;
}

export const Button: React.FC<ButtonProps> = ({
  variant = 'primary',
  size = 'medium',
  disabled = false,
  fullWidth = false,
  onClick,
  children,
}) => {
  const buttonClasses = [
    'btn',
    `btn-${variant}`,
    `btn-${size}`,
    disabled ? 'btn-disabled' : '',
    fullWidth ? 'btn-full-width' : '',
  ].filter(Boolean).join(' ');

  const handleClick = (event: React.MouseEvent<HTMLButtonElement>) => {
    if (!disabled && onClick) {
      onClick(event);
    }
  };

  return (
    <button
      className={buttonClasses}
      disabled={disabled}
      onClick={handleClick}
    >
      {children}
    </button>
  );
};

// packages/stencil-components/src/components/button-component/button-component.tsx
import { Component, Prop, h, Event, EventEmitter } from '@stencil/core';

@Component({
  tag: 'pv-button-component',
  styleUrl: 'button-component.scss',
  shadow: true,
})
export class ButtonComponent {
  /**
   * The button variant style
   */
  @Prop() variant: 'primary' | 'secondary' | 'outline' | 'danger' = 'primary';

  /**
   * The button size
   */
  @Prop() size: 'small' | 'medium' | 'large' = 'medium';

  /**
   * If true, the button is disabled
   */
  @Prop() disabled: boolean = false;

  /**
   * If true, the button will take full width of container
   */
  @Prop() fullWidth: boolean = false;

  /**
   * Emitted when the button is clicked
   */
  @Event() buttonClick!: EventEmitter<MouseEvent>;

  handleClick = (event: MouseEvent) => {
    if (!this.disabled) {
      this.buttonClick.emit(event);
    }
  }

  render() {
    const buttonClasses = {
      'btn': true,
      [`btn-${this.variant}`]: true,
      [`btn-${this.size}`]: true,
      'btn-disabled': this.disabled,
      'btn-full-width': this.fullWidth,
    };

    return (
      <button
        class={buttonClasses}
        disabled={this.disabled}
        onClick={this.handleClick}
      >
        <slot />
      </button>
    );
  }
}
