// packages/react-library/src/Badge/Badge.tsx
import React from 'react';
import './Badge.scss';

export interface BadgeProps {
  /**
   * The badge variant style
   */
  variant?: 'primary' | 'secondary' | 'outline' | 'danger' | 'success' | 'warning';

  /**
   * The badge size
   */
  size?: 'small' | 'medium' | 'large';

  /**
   * If true, the badge will be rounded
   */
  rounded?: boolean;

  /**
   * If true, the badge will be filled
   */
  filled?: boolean;

  /**
   * The badge content
   */
  children?: React.ReactNode;
}

export const Badge: React.FC<BadgeProps> = ({
  variant = 'primary',
  size = 'medium',
  rounded = false,
  filled = true,
  children,
}) => {
  const badgeClasses = [
    'badge',
    `badge-${variant}`,
    `badge-${size}`,
    rounded ? 'badge-rounded' : '',
    filled ? 'badge-filled' : 'badge-outline',
  ].filter(Boolean).join(' ');

  return (
    <span className={badgeClasses}>
      {children}
    </span>
  );
};

// packages/stencil-components/src/components/badge-component/badge.tsx
import { Component, h, Prop } from '@stencil/core';

@Component({
  tag: 'pv-badge-component',
  styleUrl: 'badge.scss',
  shadow: true,
})
export class Badge {
  /**
   * The badge variant style
   */
  @Prop() variant: 'primary' | 'secondary' | 'outline' | 'danger' | 'success' | 'warning' = 'primary';

  /**
   * The badge size
   */
  @Prop() size: 'small' | 'medium' | 'large' = 'medium';

  /**
   * If true, the badge will be rounded
   */
  @Prop({ reflect: true }) rounded: boolean = false;

  /**
   * If true, the badge will be filled
   */
  @Prop({ reflect: true }) filled: boolean = true;

  render() {
    const badgeClasses = [
      'badge',
      `badge-${this.variant}`,
      `badge-${this.size}`,
this.rounded ? 'badge-rounded' : '',
      this.filled ? '' : 'badge-outline',
    ].filter(Boolean).join(' ');

    return (
      <span class={badgeClasses}>
        <slot></slot>
      </span>
    );
  }
}
