// packages/react-library/src/Table/Table.tsx
import React, { useState, useMemo } from 'react';
import './Table.scss';

export interface TableColumn {
  key: string;
  label: string;
}

export interface TableProps {
  data?: any[];
  columns?: TableColumn[];
  className?: string;
  itemsPerPage?: number;
}

const Table: React.FC<TableProps> = ({ 
  data = [], 
  columns = [], 
  className,
  itemsPerPage = 5 
}) => {
  const [sortColumn, setSortColumn] = useState<string>('');
  const [sortDirection, setSortDirection] = useState<'asc' | 'desc'>('asc');
  const [currentPage, setCurrentPage] = useState<number>(1);

  const handleSort = (columnKey: string) => {
    if (sortColumn === columnKey) {
      setSortDirection(prev => prev === 'asc' ? 'desc' : 'asc');
    } else {
      setSortColumn(columnKey);
      setSortDirection('asc');
    }
  };

  const processedData = useMemo(() => {
    let tempData = [...data];

    if (sortColumn) {
      tempData.sort((a, b) => {
        const aValue = a[sortColumn];
        const bValue = b[sortColumn];
        if (aValue < bValue) return sortDirection === 'asc' ? -1 : 1;
        if (aValue > bValue) return sortDirection === 'asc' ? 1 : -1;
        return 0;
      });
    }

    return tempData;
  }, [data, sortColumn, sortDirection]);

  const totalPages = Math.ceil(processedData.length / itemsPerPage);
  const startIndex = (currentPage - 1) * itemsPerPage;
  const paginatedData = processedData.slice(startIndex, startIndex + itemsPerPage);

  return (
    <div className={`table-container ${className || ''}`}>
      <table>
        <thead>
          <tr>
            {columns.map((col) => (
              <th 
                key={col.key}
                onClick={() => handleSort(col.key)}
                className={`
                  sortable 
                  ${sortColumn === col.key ? (sortDirection === 'asc' ? 'sorted-asc' : 'sorted-desc') : ''}
                `}
              >
                {col.label}
                <span className="sort-icon"></span>
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {paginatedData.length > 0 ? (
            paginatedData.map((row, rowIndex) => (
              <tr key={rowIndex}>
                {columns.map((col, colIndex) => (
                  <td key={`${rowIndex}-${colIndex}`}>{row[col.key]}</td>
                ))}
              </tr>
            ))
          ) : (
            <tr>
              <td colSpan={columns.length} className="empty-state">No data available</td>
            </tr>
          )}
        </tbody>
      </table>

      {totalPages > 1 && (
        <div className="pagination">
          <button
            disabled={currentPage === 1}
            onClick={() => setCurrentPage(prev => prev - 1)}
          >
            Previous
          </button>
          <span className="page-info">
            Page {currentPage} of {totalPages}
          </span>
          <button
            disabled={currentPage === totalPages}
            onClick={() => setCurrentPage(prev => prev + 1)}
          >
            Next
          </button>
        </div>
      )}
    </div>
  );
};

export default Table;

// packages/stencil-components/src/components/table-component/table-component.tsx
import { Component, Prop, Host, h, State } from '@stencil/core';

export interface TableColumn {
  key: string;
  label: string;
}

@Component({
  tag: 'pv-table-component',
  styleUrl: 'table-component.scss',
  shadow: true,
})
export class TableComponent {
  /**
   * The table column definitions
   */
  @Prop() columns: TableColumn[] | string;

  /**
   * The table data
   */
  @Prop() data: any[] | string;

  /**
   * Items to display per page
   */
  @Prop() itemsPerPage: number = 5;

  @State() sortColumn: string = '';
  @State() sortDirection: 'asc' | 'desc' = 'asc';
  @State() currentPage: number = 1;

  private parseProp<T>(prop: T | string): T {
    if (typeof prop === 'string') {
      try {
        return JSON.parse(prop);
      } catch {
        return [] as any;
      }
    }
    return prop || ([] as any);
  }

  private handleSort(columnKey: string) {
    if (this.sortColumn === columnKey) {
      this.sortDirection = this.sortDirection === 'asc' ? 'desc' : 'asc';
    } else {
      this.sortColumn = columnKey;
      this.sortDirection = 'asc';
    }
  }

  private handlePageChange(page: number) {
    this.currentPage = page;
  }

  render() {
    const columns = this.parseProp<TableColumn[]>(this.columns);
    let data = this.parseProp<any[]>(this.data);

    // Sorting
    if (this.sortColumn) {
      data = [...data].sort((a, b) => {
        const aValue = a[this.sortColumn];
        const bValue = b[this.sortColumn];
        if (aValue < bValue) return this.sortDirection === 'asc' ? -1 : 1;
        if (aValue > bValue) return this.sortDirection === 'asc' ? 1 : -1;
        return 0;
      });
    }

    // Pagination
    const totalPages = Math.ceil(data.length / this.itemsPerPage);
    const startIndex = (this.currentPage - 1) * this.itemsPerPage;
    const paginatedData = data.slice(startIndex, startIndex + this.itemsPerPage);

    return (
      <Host>
        <div class="table-container">
          <table>
            <thead>
              <tr>
                {columns.map(col => (
                  <th
                    key={col.key}
                    onClick={() => this.handleSort(col.key)}
                    class={{
                      'sortable': true,
                      'sorted-asc': this.sortColumn === col.key && this.sortDirection === 'asc',
                      'sorted-desc': this.sortColumn === col.key && this.sortDirection === 'desc'
                    }}
                  >
                    {col.label}
                    <span class="sort-icon"></span>
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {paginatedData.length > 0 ? (
                paginatedData.map((row, rowIndex) => (
                  <tr key={rowIndex}>
                    {columns.map((col, colIndex) => (
                      <td key={`${rowIndex}-${colIndex}`}>{row[col.key]}</td>
                    ))}
                  </tr>
                ))
              ) : (
                <tr>
                  <td colSpan={columns.length} class="empty-state">No data available</td>
                </tr>
              )}
            </tbody>
          </table>

          {totalPages > 1 && (
            <div class="pagination">
              <button
                disabled={this.currentPage === 1}
                onClick={() => this.handlePageChange(this.currentPage - 1)}
              >
                Previous
              </button>
              <span class="page-info">
                Page {this.currentPage} of {totalPages}
              </span>
              <button
                disabled={this.currentPage === totalPages}
                onClick={() => this.handlePageChange(this.currentPage + 1)}
              >
                Next
              </button>
            </div>
          )}
        </div>
      </Host>
    );
  }
}
