// packages/stencil-components/src/components/legend-component/legend-component.tsx
import { Component, Prop, Host, h } from '@stencil/core';

export interface LegendItem {
  label: string;
  color: string;
}

@Component({
  tag: 'pv-legend-component',
  styleUrl: 'legend-component.scss',
  shadow: true,
})
export class LegendComponent {
  /**
   * The legend items
   */
  @Prop() items: LegendItem[] | string;

  /**
   * The legend title
   */
  @Prop() legendTitle?: string;

  private getItems(): LegendItem[] {
    if (typeof this.items === 'string') {
      try {
        return JSON.parse(this.items);
      } catch {
        return [];
      }
    }
    return this.items || [];
  }

  render() {
    const items = this.getItems();

    return (
      <Host>
        <div class="legend">
          {this.legendTitle && <h4 class="legend-title">{this.legendTitle}</h4>}
          <div class="legend-items">
            {items.map((item, index) => (
              <div key={index} class="legend-item">
                <span
                  class="legend-color"
                  style={{ backgroundColor: item.color }}
                ></span>
                <span class="legend-label">{item.label}</span>
              </div>
            ))}
          </div>
        </div>
      </Host>
    );
  }
}

// packages/react-library/src/Legend/Legend.tsx
import React from 'react';
import './Legend.scss';

export interface LegendItem {
  label: string;
  color: string;
}

export interface LegendProps {
  items: LegendItem[];
  legendTitle?: string;
  className?: string;
}

const Legend: React.FC<LegendProps> = ({ items, legendTitle, className }) => {
  return (
    <div className={`legend ${className || ''}`}>
      {legendTitle && <h4 className="legend-title">{legendTitle}</h4>}
      <div className="legend-items">
        {items.map((item, index) => (
          <div key={index} className="legend-item">
            <span
              className="legend-color"
              style={{ backgroundColor: item.color }}
            ></span>
            <span className="legend-label">{item.label}</span>
          </div>
        ))}
      </div>
    </div>
  );
};

export default Legend;
